export const site = {
  url: 'https://hyounsik.info',
  name: '이현식',
  nameEn: 'Hyoun Sik Lee',
  role: 'Flutter · iOS · Server Developer',
  location: 'Seoul, Korea',
  careerLength: '경력 15년 3개월',
  intro: [
    'iOS/Flutter 기반 앱 개발과 NodeJs와 DocumentDB, GraphDB를 이용한 백엔드 개발',
    '서비스 초기 설계 단계 부터 출시후 운영 까지 서비스 전반에 걸친 개발 경험',
    '조직의 상황에 맞는 기술 스택 선정과 마이크로 서비스 설계 및 운영',
    '서버, 클라우드, Docker를 이용하여 테스트, CI, 배포, 모니터, 비즈니스 측정등 전반적인 사용자 응용 서비스 개발-운영 경험',
  ],
  // TODO: 실제 연락처로 교체 — 현재는 더미 데이터
  contact: {
    email: 'hello@example.com',
    phone: '+82 10-0000-0000',
    github: 'https://github.com/example',
    medium: 'https://medium.com/@example',
    linkedin: 'https://linkedin.com/in/example',
  },
  companies: [
    '에이디지컴퍼니',
    '더크리스피',
    '코이랩스',
    '비엘큐',
    '에피라이브',
    '리모트몬스터',
    '레인보우브레인',
    '센텐스',
    '포니링크',
  ],
  education: {
    school: '원광대학교',
    major: '컴퓨터공학과',
    period: '2003.03 - 2010.08',
    status: '졸업',
  },
  skills: [
    'Flutter',
    'Dart',
    'Swift',
    'Objective-C',
    'TypeScript',
    'JavaScript',
    'Node.js',
    'Python',
    'Java',
    'C / C++',
    'Firebase',
    'GCP',
    'AWS',
    'MySQL',
    'Neo4j',
    'MongoDB',
    'CouchDB',
    'Git',
  ],
  awards: [
    {
      title: 'Product of the Day — Product Hunt',
      url: 'https://www.producthunt.com/products/effy',
    },
  ],
} as const;
